# Generated by Django 4.2.4 on 2023-08-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_category_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='categoryModels',
        ),
    ]
