# Generated by Django 4.2.4 on 2023-08-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodels',
            name='categories',
            field=models.ManyToManyField(related_name='post', to='blog.categorymodels'),
        ),
    ]
