# Generated by Django 4.2.4 on 2023-08-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_commentmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contact',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.AddField(
            model_name='postmodels',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
