# Generated by Django 4.2.4 on 2023-08-05 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_categorymodels_categorymodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountModel',
        ),
    ]
