from .homepage import *
from .profile import *
from .categoryDetail import *
from .mypost import *
from .singlePost import *
from .addpost import *
from .updatePost import *
from .deletePost import *
from .signout import *
from .changePassword import *